### ISSUE TITLE
AAPM dataset 

### ISSUE THREAD

**Issue by chenjiachengzzz** [mars11121/DuDoTrans#1]
尊敬的作者您好，感谢您做出这么棒的工作，并且贡献出来，我对aapm数据的处理还是有些疑惑，想要请教您.
请问使用的是1mm还是3mm的数据， 您是否使用了别的数据预处理
希望得到您的回答

**Comment by cewang-sysu** [comment]
> 

Thanks for your attention. The data spacing is 1mm. The experiments are conducted without additional preprocessing, and the simulation is from ODL library.
