### ISSUE TITLE
output of SRT

### ISSUE THREAD

**Issue by master220022** [mars11121/DuDoTrans#2]
王老师您好！对于SRT正弦图增强网络的输出我有一些疑问，该网络的输出是不是仍然是稀疏视角下的正弦图？

**Comment by cewang-sysu** [comment]
> 王老师您好！对于SRT正弦图增强网络的输出我有一些疑问，该网络的输出是不是仍然是稀疏视角下的正弦图？

Definitely, and the supervision signal of SRT is GT sinogram, therefore the output is still SV sinogram.
