### ISSUE TITLE
如何预处理AAPM数据？

### ISSUE THREAD

**Issue by Nioolek** [mars11121/DuDoTrans#3]
你好，非常感谢您开源了您的相关代码。
想请问一下，下载下来的AAPM数据，只有 projection data 和 image data ，但是网络的输入应该是正弦图？想请问一下如何生成正弦图呢？

**Comment by cewang-sysu** [comment]
> 

The input to the network is only the CT image, and the dataloader will process it and generate simulated sinograms.

**Comment by Nioolek** [comment]
> > 
> 
> The input to the network is only the CT image, and the dataloader will process it and generate simulated sinograms.

Thank you for your reply. 
But the image data format of `AAPM dataset ` is `.ima`, not `dcm`.  I think the code only can read `dcm`, so should I convert `ima` to `dcm` ?

**Comment by cewang-sysu** [comment]
> > > 
> > 
> > 
> > The input to the network is only the CT image, and the dataloader will process it and generate simulated sinograms.
> 
> Thank you for your reply. But the image data format of `AAPM dataset ` is `.ima`, not `dcm`. I think the code only can read `dcm`, so should I convert `ima` to `dcm` ?

The AAPM data format, which I downloaded two years ago, is .dcm. You can also try other datasets whose format is .dcm with the code. Otherwise, you can also rewrite a new dataloader, with the correct normalization.

**Comment by Nioolek** [comment]
OK. thank you for your reply
